### ISSUE TITLE
unwrap() on ConsumerError(DetachedInstruction)

### ISSUE THREAD

**Issue by fkaa** [google/rspirv#32]
I'm trying to parse a SPIR-V file generated by DXC, but getting error on parsing. Not sure if this is a rspirv or DXC issue.

```rust
extern crate rspirv;

fn main() {
    let spirv = include_bytes!("shader.spirv");

    let mut loader = rspirv::mr::Loader::new();
    rspirv::binary::parse_bytes(&spirv[..], &mut loader).unwrap();
    let module = loader.module();
}
```
<details>
 <summary>shader.spirv (disassembled)</summary>

```asm
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 24
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %vs "vs" %in_var_A %gl_Position
               OpSource HLSL 600
               OpName %vs "vs"
               OpName %in_var_A "in.var.A"
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %in_var_A Location 0
       %void = OpTypeVoid
          %6 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_ptr_Input_v4float = OpTypePointer Input %v4float
%_ptr_Output_v4float = OpTypePointer Output %v4float
    %float_1 = OpConstant %float 1
       %bool = OpTypeBool
   %in_var_A = OpVariable %_ptr_Input_v4float Input
%gl_Position = OpVariable %_ptr_Output_v4float Output
         %vs = OpFunction %void None %6
         %13 = OpLabel
         %14 = OpLoad %v4float %in_var_A
         %15 = OpCompositeExtract %float %14 0
         %16 = OpFOrdEqual %bool %15 %float_1
               OpSelectionMerge %17 None
               OpBranchConditional %16 %18 %19
         %18 = OpLabel
         %20 = OpExtInst %v4float %1 FAbs %14
         %21 = OpFNegate %v4float %20
               OpBranch %17
         %19 = OpLabel
         %22 = OpVectorShuffle %v4float %14 %14 3 2 1 0
               OpBranch %17
         %17 = OpLabel
         %23 = OpPhi %v4float %21 %18 %22 %19
               OpStore %gl_Position %23
               OpReturn
               OpFunctionEnd
```
</details>
<details>
 <summary>shader.hlsl</summary>

```hlsl
struct VSInput
{
    float4 a : A;
};

float4 vs(VSInput input) : SV_Position
{
    if (input.a.x == 1.0) {
	return -abs(input.a);
    } else {
        return input.a.wzyx;
    }
}
```
</details>
<details>
 <summary>stacktrace</summary>

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConsumerError(DetachedInstruction)', libcore\res
ult.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:77
  10: core::result::unwrap_failed<rspirv::binary::parser::State>
             at C:\projects\rust\src\libcore\macros.rs:26
  11: core::result::Result<(), rspirv::binary::parser::State>::unwrap<(),rspirv::binary::parser::State>
             at C:\projects\rust\src\libcore\result.rs:782
  12: simple::main
             at .\examples\simple.rs:7
  13: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  14: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  15: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  18: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  19: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  20: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  21: main
  22: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  23: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: BaseThreadInitThunk
  25: RtlUserThreadStart
```
</details>

**Comment by fkaa** [comment]
So the crash happens on the last `OpStore` instruction and I think I've tracked it down to `OpPhi` [being treated as a block terminator](https://github.com/google/rspirv/blob/cddf49f43133d7b91091c2c99134bb51fdb4f8d9/rspirv/grammar/reflect.rs#L114) when it shouldn't ([spec](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Branch))
