### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by thavlik** [google/rspirv#34]
```
Thomass-MacBook-Pro:Development thomashavlik$ git clone https://github.com/google/rspirv.git
Thomass-MacBook-Pro:Development thomashavlik$ cd rspirv
Thomass-MacBook-Pro:rspirv thomashavlik$ RUST_BACKTRACE=1 cargo test
   Compiling rspirv-codegen v0.1.0 (/Users/thomashavlik/Development/rspirv/codegen)
error: failed to run custom build command for `rspirv-codegen v0.1.0 (/Users/thomashavlik/Development/rspirv/codegen)`
process didn't exit successfully: `/Users/thomashavlik/Development/rspirv/target/debug/build/rspirv-codegen-d054220d5ae98f1e/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:325
   7: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:95
   8: core::result::unwrap_failed
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/result.rs:808
  10: build_script_build::main
             at codegen/build.rs:88
  11: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:102
  14: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  15: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  16: build_script_build::main
```

OS X 10.14.3
Stable branch; cargo 1.32.0 (8610973aa 2019-01-02); rustc 1.32.0 (9fda7c223 2019-01-16)

**Comment by antiagainst** [comment]
There are multiple crates inside this repo. The `codegen` crate is intended to automatically generate code used by other crates. It uses SPIR-V JSON grammar from [SPIRV-Headers](https://github.com/KhronosGroup/SPIRV-Headers). So you'll need to `git submodule update --init` to clone the repo to build `codegen` crate. But `codegen` crate is something you don't need to bother if not modifying other crates. I have explained more with https://github.com/google/rspirv/commit/9af748bb3b0af25227214ed0f1a35a972751df6b. Hopefully it clears up.

**Comment by thavlik** [comment]
Yep, `git submodule update --init` fixed it. Thank you.
